### ISSUE TITLE
Stop lima VM instead of deleting it?

### ISSUE THREAD

**Issue by felipecruz91** [developer-guy/buildkit-machine#2]
Hi,

When stopping the `buildkit-machine` the lima VM is deleted:

https://github.com/developer-guy/buildkit-machine/blob/6863e065d17f1b7f45bd0d746ca6c4a064a576c0/cmd/start.go#L170

This means that the next time that I run `buildkit-machine start`, the lima VM needs to be created from scratch. I wonder if it'd make more sense to just stop it instead?

**Comment by Dentrax** [comment]
+1, That makes sense! Feel free to contribute. 🙏
